### PR TITLE
✨ feat(giveaway): Allow whitelisting of servers to snipe giveaways on

### LINKED ISSUE #158: [Feature Request] snipe giveaway 1 server only
I Would like to snipe giveaway only 1 server it's possible to make?

### PR DESCRIPTION
**Pull request by Wyatt-Stanke**
This allows for you to specify a server whitelist to snipe giveaways on.
Extra info: This is my first commit to a public repo! ✨yay!✨ 

Closes #158

### CODE REVIEW

**Comment by MaiSan0001** [comment]
> This allows for you to specify a server whitelist to snipe giveaways on.
> Extra info: This is my first commit to a public repo! ✨yay!✨
> 
> Closes #158

image
is this okay?

**Comment by MaiSan0001** [comment]
> > This allows for you to specify a server whitelist to snipe giveaways on.
> > Extra info: This is my first commit to a public repo! ✨yay!✨
> > Closes #158
> 
> image
> is this okay?

image
 or this?

**Comment by slow** [comment]
> > > This allows for you to specify a server whitelist to snipe giveaways on.
> > > Extra info: This is my first commit to a public repo! ✨yay!✨
> > > Closes #158
> > 
> > 
> > image
> > is this okay?
> 
> image
> or this?

image 

this is the only thing that will work

**Pull request merged**
